Resources:
  EmailsUsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-EmailsUsers-table
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1  
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: idUser
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: studentIndex
          KeySchema:
            - AttributeName: idUser
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1  
